
const char *helptext[] = {
"HELP",
"",
"  Right mouse ................. Describe entry under mouse cursor",
"",
"FILE",
"",
"  F2 .......................... Save current page",
"  F3 .......................... Load current page",
"  Ctrl + F4 ................... Nuke current page",
"",
"PLAYBACK / RECORD",
"",
"  F7 or KP Dot ................ Toggle record notes",
"  Left Shift + KP1..KP5 ....... Toggle record percussion channel",
"  KP8 and KP9 ................. Toggle record mouse into control parameters",
"",
"  F5 .......................... Play / pause Song from cursor position",
"  F6 or KP Enter .............. Play / pause Loop from cursor position",
"  F8 or KP 0 .................. Stop",
"  Ctrl + F8 or KP 0 ........... Silence",
"",
"  Right Alt ................... Play current Row",
"  Space ....................... Play current Row and advance (play single step)",
"",
"  Ctrl + 1..6 ................. Mute / unmute channel",
"  Ctrl + KP1..KP5 ............. Mute / unmute percussion channel",
"",
"VIEW",
"",
"  Enter ....................... Toggle front page (yellow) / back page (blue)",
"  Tab ......................... Toggle pattern / instrument cursor",
"  Left Shift + Tab............. Hide instrument table",
"",
"NAVIGATION / SELECTION",
"",
"  Arrows ...................... Move cursor and mark",
"  Left Shift + Arrows ......... Move cursor and mark end",
"  Left Ctrl + Arrows .......... Move cursor and mark start",
"  Left Shift + Ctrl + Arrows .. Move cursor only",
"",
"  Page up ..................... Move cursor and mark up 16 lines",
"  Page down ................... Move cursor and mark down 16 lines",
"",
"  Left mouse click ............ Set cursor and mark",
"  Left mouse drag ............. Select region (set mark start and end)",
"  Left Shift + LM drag ........ Move Region (move mark start and end)",
"  Click screen border ......... Scroll up / down",
"",
"  Alt + Z ..................... Reset mark to cursor",
"  Alt + X ..................... Toggle select whole line",
"  Alt + C ..................... Toggle select whole loop",
"",
"PATTERN EDIT",
"",
"  Right Shift ................. Count in beat",
"",
"  Insert ...................... Insert line",
"  Delete ...................... Delete line",
"  ",
"  Ctrl + C .................... Copy mark",
"  Ctrl + V .................... Save mark",
"",
"  Ctrl + Z .................... Undo",
"  Ctrl + Y .................... Redo",
"",
"  KP/ and KP* ................. Change Tempo",
"",
"VALUE ENTRY",
"",
"  0..9, A..F .................. Enter Value",
"",
"FLAG ENTRY",
"",
"  1 or 0 ...................... Toggle Flag",
"  2 or = or KP+ ............... Set Flag",
"  3 or - or KP- ............... Reset Flag",
"",
"NOTE ENTRY",
"                                            ┌─┬───┬───┬─┬─┬───┬───┬───┬─┬───┐",
"  [ and ] ..................... Octave      │ │   │   │ │ │   │   │   │ │   │",
"                                            │ │   │   │ │ │   │   │   │ │   │",
"  KP1 ......................... Hi-hat      │ │ 2 │ 3 │ │ │ 5 │ 6 │ 7 │ │   │",
"  KP2 ......................... Cymbal      │ │ S │ F │ │ │ H │ J │ K │ │   │",
"  KP3 ......................... Tomtom      │ └─┬─┴─┬─┘ │ └─┬─┴─┬─┴─┬─┘ │   │",
"  KP4 ......................... Snare drum  │ Q │ W │ E │ R │ T │ Y │ U │ I │",
"  KP5 ......................... Base drum   │ Z │ X │ C │ V │ B │ N │ M │ , │",
"                                            └───┴───┴───┴───┴───┴───┴───┴───┘"
};

